name: Deploy GO

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: ${{ secrets.AZURE_CONTAINER_APP_NAME }}
          resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
          location: southeastasia  
          imageToDeploy: ghcr.io/${{ github.repository_owner }}/mockservice:${{ github.sha }}
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.GHCR_USERNAME }}
          registryPassword: ${{ secrets.GHCR_PAT }}

