name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/tripay-mock-server:latest .
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/tripay-mock-server:latest

          name: Deploy to Azure Container App
